name: Push components to Espressif Component Service

on:
  push:
    branches:
      - master

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'recursive'
      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          directories: >
            components/audio/pwm_audio;
            components/bluetooth/ble_conn_mgr;
            components/bluetooth/ble_services;
            components/bluetooth/ble_profiles/esp/ble_ota;
            components/bluetooth/ble_profiles/std/ble_anp;
            components/bluetooth/ble_profiles/std/ble_hrp;
            components/bluetooth/ble_profiles/std/ble_htp;
            components/bootloader_support_plus;
            components/button;
            components/display/lcd/esp_lcd_gc9b71;
            components/display/lcd/esp_lcd_panel_io_additions;
            components/display/lcd/esp_lcd_nv3022b;
            components/display/lcd/esp_lcd_sh8601;
            components/display/lcd/esp_lcd_spd2010;
            components/display/lcd/esp_lcd_st7701;
            components/display/lcd/esp_lcd_st77903_rgb;
            components/display/lcd/esp_lcd_st77916;
            components/display/lcd/esp_lcd_st77922;
            components/display/lcd_touch/esp_lcd_touch_spd2010;
            components/display/lcd_touch/esp_lcd_touch_st7123;
            components/elf_loader;
            components/extended_vfs;
            components/gprof;
            components/ir/ir_learn;
            components/knob;
            components/led/led_indicator;
            components/led/lightbulb_driver;
            components/motor/esp_sensorless_bldc_control;
            components/motor/esp_simplefoc;
            components/openai;
            components/sensors/humiture/aht20;
            components/sensors/radar/at581x;
            components/usb/esp_msc_ota;
            components/usb/esp_tinyuf2;
            components/usb/iot_usbh;
            components/usb/iot_usbh_cdc;
            components/usb/iot_usbh_modem;
            components/usb/usb_device_uvc;
            components/usb/usb_stream;
            components/utilities/xz;
            components/zero_detection;
            tools/cmake_utilities;
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
